import React, { useState } from 'react';
import { gql, GraphQLClient } from 'graphql-request';
import Head from 'next/head';
import Image from 'next/image';
import Sections from '../components/movie-section/Sections';

export default function Home({ videos }) {
  console.log(videos);
  const banner = (picture) => {
    return picture[Math.floor(Math.random() * picture.length)];
  };

  return (
    <div className="bg-bg min-w-screen h-[400vh] scrollbar-hide">
      <Head>
        <title>H-MOVIES</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative w-screen h-[70vh] mb-8">
        <Image
          src={banner(videos).thumbnail.url}
          alt="Banner"
          layout="fill"
          objectFit="cover"
        />
      </div>

      <Sections data={videos} />
    </div>
  );
}

export const getStaticProps = async () => {
  const url = process.env.GRAPH_CMS_ENDPOINT;

  const graphQLClient = new GraphQLClient(url, {
    headers: {
      Authorization: process.env.GRAPH_CMS_TOKEN,
    },
  });

  const query = gql`
    query {
      videos {
        createdAt
        id
        title
        description
        seen
        slug
        tags
        thumbnail {
          url
        }
        mp4 {
          url
        }
      }
    }
  `;
  const data = await graphQLClient.request(query);
  const videos = data.videos;
  console.log(videos);
  return {
    props: {
      videos,
    },
  };
};
